application: buzzingcat
version: 1
runtime: python
api_version: 1

handlers:
- url: /images
  static_dir: images

- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: buzzingcat.py

inbound_services:
- xmpp_message
